export { InMemoryProvider, createInMemoryProvider, createDefaultInMemoryProvider } from './memory/index.js';
export type { InMemoryConfig } from './memory/index.js';
export { SQLiteMemoryProvider } from './sqlite/index.js';
export type { SQLiteMemoryConfig } from './sqlite/index.js';
export { SupabaseMemoryProvider, createSupabaseMemoryProvider, SUPABASE_MEMORY_MIGRATION } from './supabase/index.js';
export type { SupabaseMemoryConfig } from './supabase/index.js';
export { NeonMemoryProvider, createNeonMemoryProvider, createNeonConnectionString } from './neon/index.js';
export type { NeonMemoryConfig } from './neon/index.js';
export { PostgresMemoryProvider, createPostgresMemoryProvider, createDefaultPostgresProvider, createPostgresConnectionString } from './postgres/index.js';
export type { PostgresMemoryConfig } from './postgres/index.js';
import { MemoryProviderType } from '../../../types/agent.js';
import { InMemoryProvider, InMemoryConfig } from './memory/index.js';
import { SQLiteMemoryProvider, SQLiteMemoryConfig } from './sqlite/index.js';
import { SupabaseMemoryProvider, SupabaseMemoryConfig } from './supabase/index.js';
import { NeonMemoryProvider, NeonMemoryConfig } from './neon/index.js';
import { PostgresMemoryProvider, PostgresMemoryConfig } from './postgres/index.js';
export type MemoryProviderConfig = InMemoryConfig | SQLiteMemoryConfig | SupabaseMemoryConfig | NeonMemoryConfig | PostgresMemoryConfig;
export declare function createMemoryProvider(type: MemoryProviderType, config: MemoryProviderConfig): InMemoryProvider | SQLiteMemoryProvider | SupabaseMemoryProvider | NeonMemoryProvider | PostgresMemoryProvider;
export declare function getMemoryProviderTypes(): {
    type: MemoryProviderType;
    name: string;
    description: string;
    supportsVectorSearch: boolean;
    isPersistent: boolean;
}[];
